spring:
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-master.xml
    clear-checksums: false
    drop-first: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labo
    username: root
    password: admin!123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
