spring:
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-master.xml
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labo
    username: root
    password: admin!123
  jpa:
    database-platform: MYSQL
