INSERT INTO `icd` (`code1`, `name1`, `code2`, `name2`)
VALUES ('A', 'Analityka', 'A01', 'Badanie ogólne moczu (profil)'),
       ('A', 'Analityka', 'A03', 'Badanie płynu mózgowo-rdzeniowego'),
       ('A', 'Analityka', 'A05', 'Badanie płynu z jamy ciała (opłucnej, otrzewnej)'),
       ('A', 'Analityka', 'A07', 'Białko w moczu'),
       ('A', 'Analityka', 'A09', 'Bilirubina w moczu'),
       ('A', 'Analityka', 'A11', 'Ciała ketonowe w moczu'),
       ('A', 'Analityka', 'A12', 'Ciężar właściwy moczu'),
       ('A', 'Analityka', 'A13', 'Erytrocyty/ hemoglobina w moczu'),
       ('A', 'Analityka', 'A14', 'Leukocyty w moczu'),
       ('A', 'Analityka', 'A15', 'Glukoza w moczu'),
       ('A', 'Analityka', 'A17', 'Krew utajona w kale'),
       ('A', 'Analityka', 'A19', 'Osad moczu'),
       ('A', 'Analityka', 'A21', 'Pasożyty/ jaja pasożytów w kale'),
       ('A', 'Analityka', 'A23', 'Resztki pokarmowe w kale'),
       ('A', 'Analityka', 'A25', 'Urobilinogen w moczu'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C01', 'Erytroblasty'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C02', 'Erytrocyty – liczba'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C03', 'Erytrocyty – oporność osmotyczna'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C05', 'Erytrocyty – próba Hama'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C07', 'Erytrocyty – próba sacharozowa'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C09', 'Erytrogram'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C10', 'Inne antygeny grupowe krwinek czerwonych'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C11', 'Fosfataza zasadowa granulocytów'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C13', 'Granulocyty – badanie aktywności fagocytarnej'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C15', 'Granulocyty zasadochłonne – test bezpośredniej degranulacji'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C19', 'Hemoglobina, rozdział'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C21', 'Leukocyty – badanie aktywności peroksydazy (POX)'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C23', 'Leukocyty – badanie aktywności esterazy nieswoistej'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C27', 'Leukocyty – badanie immunofenotypowe komórek blastycznych'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C29', 'Leukocyty – barwienie sudanem czarnym B'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C30', 'Leukocyty – liczba'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C31', 'Leukocyty – reakcja PAS'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C32', 'Leukocyty – obraz odsetkowy'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C33', 'Limfadenogram'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C35', 'Limfoblasty'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C37', 'Limfocyty B'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C39', 'Limfocyty BCD5+'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C41', 'Limfocyty T'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C43', 'Limfocyty TCD4+'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C45', 'Limfocyty TCD8+'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C47', 'Metamielocyty'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C49', 'Mieloblasty'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C51', 'Mielogram'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C53', 'Morfologia krwi 8-parametrowa'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C55', 'Morfologia krwi, z pełnym różnicowaniem granulocytów'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C57', 'Objętość krwi krążącej'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C59', 'Odczyn opadania krwinek czerwonych'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C61', 'Płytki krwi - badanie adhezji'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C63', 'Płytki krwi - badanie agregacji'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C65', 'Płytki krwi - czas przeżycia'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C66', 'Płytki krwi – liczba'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C67', 'Promielocyty'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C69', 'Retykulocyty'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C71', 'Splenogram'),
       ('C', 'Morfologia krwi i badania hematologiczne', 'C73', 'Test hamowania migracji makrofagów'),
       ('E', 'Serologia grup krwi', 'E05', 'Badanie w kierunku nieregularnych przeciwciał'),
       ('E', 'Serologia grup krwi', 'E20', 'Próba zgodności serologicznej'),
       ('E', 'Serologia grup krwi', 'E21', 'Diagnostyka konfliktu matczyno-płodowego'),
       ('E', 'Serologia grup krwi', 'E31', 'Kwalifikacja do podania immunoglobuliny anty-Rh(D) '),
       ('E', 'Serologia grup krwi', 'E64', 'Diagnostyka niedokrwistości autoimmunohemolitycznej'),
       ('E', 'Serologia grup krwi', 'E65', 'Oznaczenie grupy krwi układu ABO i Rh'),
       ('F', 'Wirusologia', 'F01', 'Adenovirus Antygen'),
       ('F', 'Wirusologia', 'F03', 'Adenovirus Przeciwciała IgA (anty-Adenovirus IgA)'),
       ('F', 'Wirusologia', 'F05', 'Adenovirus Przeciwciała IgG (anty-Adenovirus IgG)'),
       ('F', 'Wirusologia', 'F07', 'Adenovirus Przeciwciała IgM (anty-Adenovirus IgM)'),
       ('F', 'Wirusologia', 'F09', 'Adenovirus IgG/ IgM Przeciwciała (anty-Adenovirus IgG/ IgM)'),
       ('F', 'Wirusologia', 'F11', 'Astrovirus Antygen'),
       ('F', 'Wirusologia', 'F13', 'Bunyavirus IgG/ IgM Przeciwciała'),
       ('F', 'Wirusologia', 'F15', 'Cytomegalovirus (CMV) Antygen pp65'),
       ('F', 'Wirusologia', 'F17', 'Cytomegalovirus (CMV) Przeciwciała IgA (anty-Cytomegalovirus IgA)'),
       ('F', 'Wirusologia', 'F19', 'Cytomegalovirus (CMV) Przeciwciała IgG (anty-Cytomegalovirus IgG)'),
       ('F', 'Wirusologia', 'F21', 'Cytomegalovirus (CMV) Przeciwciała IgG - test potwierdzenia'),
       ('F', 'Wirusologia', 'F22', 'Cytomegalovirus (CMV) Przeciwciała IgG - Awidność'),
       ('F', 'Wirusologia', 'F23', 'Cytomegalovirus (CMV) Przeciwciała IgM (anty-Cytomegalovirus IgM)'),
       ('F', 'Wirusologia', 'F24', 'Cytomegalovirus (CMV) Przeciwciała IgM - test potwierdzenia'),
       ('F', 'Wirusologia', 'F25', 'Cytomegalovirus (CMV) Przeciwciała IgG/ IgM'),
       ('F', 'Wirusologia', 'F26', 'Cytomegalovirus (CMV) DNA'),
       ('F', 'Wirusologia', 'F27', 'Enterovirus Przeciwciała IgA (anty-Enterovirus IgA)'),
       ('F', 'Wirusologia', 'F28', 'Enterovirus Przeciwciała IgM (anty-Enterovirus IgM)'),
       ('F', 'Wirusologia', 'F29', 'Enterovirus IgG Przeciwciała (anty-Enterovirus IgG)'),
       ('F', 'Wirusologia', 'F30', 'HTLV1 Antygen'),
       ('F', 'Wirusologia', 'F31', 'HTLV 1/2 Antygen'),
       ('F', 'Wirusologia', 'F32', 'HTLV 1/2 Przeciwciała'),
       ('F', 'Wirusologia', 'F33', 'Parvovirus B19 Przeciwciała IgG (anty-Parvovirus IgG)'),
       ('F', 'Wirusologia', 'F34', 'Parvovirus B19 Przeciwciała IgM (anty-Parvovirus IgM)'),
       ('F', 'Wirusologia', 'F35', 'Parvovirus B19 IgG/ IgM Przeciwciała'),
       ('F', 'Wirusologia', 'F36', 'Rotavirus Antygen'),
       ('F', 'Wirusologia', 'F37', 'Rotavirus/ Adenovirus Antygen'),
       ('F', 'Wirusologia', 'F38', 'Wirus brodawczaka ludzkiego (HPV) HPV-DNA'),
       ('F', 'Wirusologia', 'F39', 'Wirus Dengue Przeciwciała IgG (anty-Dengue IgG)'),
       ('F', 'Wirusologia', 'F40', 'Wirus Dengue Przeciwciała IgM (anty-Dengue IgM)'),
       ('F', 'Wirusologia', 'F41', 'Wirus Dengue Przeciwciała IgG/ IgM (anty-Dengue IgG/ IgM)'),
       ('F', 'Wirusologia', 'F42', 'Wirus Epstein Barr Przeciwciała IgG (anty-Epstein-Barr (EA) IgG'),
       ('F', 'Wirusologia', 'F43', 'Wirus Epstein Barr Przeciwciała IgM (anty-Epstein-Barr (EA) IgM'),
       ('F', 'Wirusologia', 'F44', 'Wirus Epstein Barr Przeciwciała IgA (anty Epstein-Barr (EBNA) IgA'),
       ('F', 'Wirusologia', 'F45', 'Wirus Epstein Barr Przeciwciała IgG (anty-Epstein-Barr (EBNA) IgG'),
       ('F', 'Wirusologia', 'F46', 'Wirus Epstein Barr Przeciwciała IgM (anty-Epstein-Barr (EBNA) IgM'),
       ('F', 'Wirusologia', 'F47', 'Wirus Epstein Barr Przeciwciała IgA (anty-Epstein-Barr (VCA) IgA'),
       ('F', 'Wirusologia', 'F48', 'Wirus Epstein Barr Przeciwciała IgG (anty-Epstein-Barr (VCA) IgG'),
       ('F', 'Wirusologia', 'F49', 'Wirus Epstein Barr Przeciwciała IgG (anty-Epstein-Barr (VCA) IgG (ilościowy)'),
       ('F', 'Wirusologia', 'F50', 'Wirus Epstein Barr Przeciwciała IgM (anty-Epstein-Barr (VCA) IgM'),
       ('F', 'Wirusologia', 'F51', 'Wirus Epstein Barr Przeciwciała IgG/ IgM (anty-Epstein-Barr IgG/ IgM)'),
       ('F', 'Wirusologia', 'F52', 'Wirus Epstein Barr Przeciwciała IgA/ IgM'),
       ('F', 'Wirusologia', 'F53', 'Wirus Epstein Barr IgG Przeciwciała'),
       ('F', 'Wirusologia', 'F54', 'Wirus Epstein Barr Przeciwciała IgG - test potwierdzenia'),
       ('F', 'Wirusologia', 'F55', 'Wirus Epstein Barr Przeciwciała heterofilne'),
       ('F', 'Wirusologia', 'F56', 'Wirus Epstein Barr Przeciwciała IgM'),
       ('F', 'Wirusologia', 'F57', 'Wirus Herpes Simplex typu 1 Przeciwciała IgA (anty-Herpes Simpl. V. 1 IgA)'),
       ('F', 'Wirusologia', 'F58', 'Wirus Herpes Simplex typu 1 Przeciwciała IgG'),
       ('F', 'Wirusologia', 'F59', 'Wirus Herpes Simplex typu 1 Przeciwciała IgG (ilościowo)'),
       ('F', 'Wirusologia', 'F60', 'Wirus Herpes Simplex typu 1 Przeciwciała IgM'),
       ('F', 'Wirusologia', 'F61', 'Wirus Herpes Simplex typu 1 Przeciwciała IgM (ilościowo)'),
       ('F', 'Wirusologia', 'F62', 'Wirus Herpes Simplex typu 1 Przeciwciała IgG/ IgM (anty-Herpes Simpl. V. 1 IgG/ IgM)'),
       ('F', 'Wirusologia', 'F63', 'Wirus Herpes Simplex typu 1/2 Przeciwciała IgA (anty-Herpes Simpl. V. 1/2 IgA)'),
       ('F', 'Wirusologia', 'F64', 'Wirus Herpes Simplex typu 1/2 IgG Przeciwciała (anty-Herpes Simpl. V. 1/2 IgG)'),
       ('F', 'Wirusologia', 'F65', 'Wirus Herpes Simplex typu 1/2 Przeciwciała IgM (anty-Herpes Simpl. V. 1/2 IgM)'),
       ('F', 'Wirusologia', 'F66', 'Wirus Herpes Simplex typu 2 Przeciwciała IgG (anty-Herpes Simpl. V. 2 IgG)'),
       ('F', 'Wirusologia', 'F67', 'Wirus Herpes Simplex typu 2 Przeciwciała IgG (anty-Herpes Simpl. V. 2 IgG) (ilościowo)'),
       ('F', 'Wirusologia', 'F68', 'Wirus Herpes Simplex typu 2 Przeciwciała IgA (anty-Herpes Simpl. V. 2 IgA)'),
       ('F', 'Wirusologia', 'F69', 'Wirus Herpes Simplex typu 2 Przeciwciała IgM'),
       ('F', 'Wirusologia', 'F70', 'Wirus Herpes Simplex typu 2 Przeciwciała IgM (ilościowo)'),
       ('F', 'Wirusologia', 'F71', 'Wirus Herpes Simplex typu 2 Przeciwciała IgG/ IgM (anty-Herpes Simpl. V. 2 IgG/ IgM)'),
       ('F', 'Wirusologia', 'F72', 'Wirus Herpes Simplex typu 1/2 Przeciwciała IgG/ IgM screening (anty-Herpes Simpl. V. 1/2 IgG/ IgM)'),
       ('F', 'Wirusologia', 'F73', 'Wirus Influenza A Antygen'),
       ('F', 'Wirusologia', 'F74', 'Wirus Influenza A Przeciwciała IgA (anty-Influenza IgA)'),
       ('F', 'Wirusologia', 'F75', 'Wirus Influenza A Przeciwciała IgG (anty-Influenza IgG)'),
       ('F', 'Wirusologia', 'F76', 'Wirus Influenza A Przeciwciała IgM (anty-Influenza IgM)'),
       ('F', 'Wirusologia', 'F77', 'Wirus Influenza A Przeciwciała IgG/ IgM (anty-Influenza IgG/ IgM)'),
       ('F', 'Wirusologia', 'F78', 'Wirus Influenza B Antygen'),
       ('F', 'Wirusologia', 'F79', 'Wirus Influenza B Przeciwciała IgA (anty-Influenza IgA)'),
       ('F', 'Wirusologia', 'F80', 'Wirus Influenza B Przeciwciała IgG (anty-Influenza IgG)'),
       ('F', 'Wirusologia', 'F81', 'Wirus Influenza B Przeciwciała IgM (anty-Influenza IgM)'),
       ('F', 'Wirusologia', 'F82', 'Wirus Influenza B Przeciwciała IgG/ IgM (anty-Influenza IgG/ IgM)'),
       ('F', 'Wirusologia', 'F83', 'Wirus Influenza, Parainfluenzy, Adenowirus Antygen'),
       ('F', 'Wirusologia', 'F84', 'Wirus kleszczowego zapalenia mózgu (TBE) IgG (anty-TBE virus IgG)'),
       ('F', 'Wirusologia', 'F85', 'Wirus kleszczowego zapalenia mózgu (TBE) IgM (anty-TBE virus IgM)'),
       ('F', 'Wirusologia', 'F86', 'Wirus kleszczowego zapalenia mózgu (TBE) IgG/ IgM (anty-TBE virus IgG/ IgM)'),
       ('F', 'Wirusologia', 'F87', 'Wirus/ przeciwciała nabytego niedoboru odporności (HIV) Antygen p24'),
       ('F', 'Wirusologia', 'F88', 'Wirus/ przeciwciała nabytego niedoboru odporności (HIV) Antygen (ilościowo)'),
       ('F', 'Wirusologia', 'F89', 'Wirus/ przeciwciała nabytego niedoboru odporności (HIV) Przeciwciała całkowite'),
       ('F', 'Wirusologia', 'F90', 'Wirus/ przeciwciała nabytego niedoboru odporności (HIV) Przeciwciała (test potwierdzający)'),
       ('F', 'Wirusologia', 'F91', 'Wirus/ przeciwciała nabytego niedoboru odporności (HIV) Antygen/ Przeciwciała'),
       ('F', 'Wirusologia', 'F92', 'Wirus/ przeciwciała nabytego niedoboru odporności (HIV) RNA / DNA'),
       ('F', 'Wirusologia', 'F93', 'Wirus nagnminnego zapalenia ślinianek przyusznych IgM (anty-Rubulavirus Antygen M) (Rubulavirus)'),
       ('F', 'Wirusologia', 'F94', 'Wirus nagnminnego zapalenia ślinianek przyusznych (Rubulavirus) IgG (anty-Rubulavirus IgG)'),
       ('F', 'Wirusologia', 'F95',
        'Wirus nagminnego zapalenia ślinianek przyusznych (Rubulavirus) Przeciwciała IgG/ IgM (anty-Rubulavirus IgG/ IgM)'),
       ('F', 'Wirusologia', 'F96', 'Wirus Odry (Morbillivirus) Przeciwciała IgG (anty-Morbillivirus IgG)'),
       ('F', 'Wirusologia', 'F97', 'Wirus Odry (Morbillivirus) Przeciwciała IgM (anty-Morbillivirus IgM)'),
       ('F', 'Wirusologia', 'F98', 'Wirus Parainfluenzy typ 1 Przeciwciała IgG'),
       ('F', 'Wirusologia', 'F99', 'Wirus Parainfluenzy typ 1 Przeciwciała IgG/ IgM (anty-Parainfluenza 1 IgG/ IgM)'),
       ('G', 'Badania układu krzepnięcia', 'G01', '?-2-antyplazmina'),
       ('G', 'Badania układu krzepnięcia', 'G03', 'Antytrombina III (AT III)'),
       ('G', 'Badania układu krzepnięcia', 'G05', 'Białko C'),
       ('G', 'Badania układu krzepnięcia', 'G07', 'Białko S'),
       ('G', 'Badania układu krzepnięcia', 'G09', 'Czas częściowej tromboplastyny (PTT)'),
       ('G', 'Badania układu krzepnięcia', 'G11', 'Czas częściowej tromboplastyny po aktywacji (APTT)'),
       ('G', 'Badania układu krzepnięcia', 'G13', 'Czas fibrynolizy (lizy skrzepu euglobulin)'),
       ('G', 'Badania układu krzepnięcia', 'G15', 'Czas krwawienia'),
       ('G', 'Badania układu krzepnięcia', 'G17', 'Czas krzepnięcia osocza po uwapnieniu'),
       ('G', 'Badania układu krzepnięcia', 'G19', 'Czas krzepnięcia pełnej krwi'),
       ('G', 'Badania układu krzepnięcia', 'G21', 'Czas protrombinowy (PT)'),
       ('G', 'Badania układu krzepnięcia', 'G23', 'Czas reptylazowy (RT)'),
       ('G', 'Badania układu krzepnięcia', 'G25', 'Czas trombinowy (TT)'),
       ('G', 'Badania układu krzepnięcia', 'G26', 'Czynnik krzepnięcia II (FII)'),
       ('G', 'Badania układu krzepnięcia', 'G28', 'Czynnik krzepnięcia IXAg (FIXAg)'),
       ('G', 'Badania układu krzepnięcia', 'G29', 'Czynnik krzepnięcia V (FV)'),
       ('G', 'Badania układu krzepnięcia', 'G31', 'Czynnik krzepnięcia VII (FVII)'),
       ('G', 'Badania układu krzepnięcia', 'G33', 'Czynnik krzepnięcia VIII (FVIII)'),
       ('G', 'Badania układu krzepnięcia', 'G34', 'Czynnik krzepnięcia VIII Ag (FVIIIAg)'),
       ('G', 'Badania układu krzepnięcia', 'G35', 'Czynnik krzepnięcia VIII - podjednostki'),
       ('G', 'Badania układu krzepnięcia', 'G37', 'Czynnik krzepnięcia X (FX)'),
       ('G', 'Badania układu krzepnięcia', 'G39', 'Czynnik krzepnięcia XI (FXI)'),
       ('G', 'Badania układu krzepnięcia', 'G41', 'Czynnik krzepnięcia XII (FXII)'),
       ('G', 'Badania układu krzepnięcia', 'G43', 'Czynnik krzepnięcia XIII (FXIII)'),
       ('G', 'Badania układu krzepnięcia', 'G45', 'Czynnik płytkowy 4'),
       ('G', 'Badania układu krzepnięcia', 'G47', 'Czynnik von Willebranda (vWF)'),
       ('G', 'Badania układu krzepnięcia', 'G49', 'D-Dimer'),
       ('G', 'Badania układu krzepnięcia', 'G53', 'Fibrynogen (FIBR)'),
       ('G', 'Badania układu krzepnięcia', 'G55', 'Fibrynopeptyd A (FIBP A)'),
       ('G', 'Badania układu krzepnięcia', 'G57', 'Fibrynopeptyd B (FIBP B)'),
       ('G', 'Badania układu krzepnięcia', 'G59', 'Fragmenty protrombiny 1 i 2'),
       ('G', 'Badania układu krzepnięcia', 'G61', 'Heparyna'),
       ('G', 'Badania układu krzepnięcia', 'G63', 'Heparyna niskocząsteczkowa'),
       ('G', 'Badania układu krzepnięcia', 'G65', 'Inhibitor aktywatora plazminogenu 1 (PAI1)'),
       ('G', 'Badania układu krzepnięcia', 'G67', 'Inhibitor aktywatora plazminogenu 2 (PAI2)'),
       ('G', 'Badania układu krzepnięcia', 'G68', 'Miedź (Cu)'),
       ('G', 'Badania układu krzepnięcia', 'G69', 'Inhibitory krzepnięcia'),
       ('G', 'Badania układu krzepnięcia', 'G70', 'Oznaczenie aktywności czynnika IX'),
       ('G', 'Badania układu krzepnięcia', 'G71', 'Kininogen (120000) (HMWK)'),
       ('G', 'Badania układu krzepnięcia', 'G73', 'Kompleks trombina/ antytrombina III (TAT)'),
       ('G', 'Badania układu krzepnięcia', 'G75', 'Monomery fibryny'),
       ('G', 'Badania układu krzepnięcia', 'G77', 'Produkty degradacji fibryny (FDP)'),
       ('G', 'Badania układu krzepnięcia', 'G79', 'Plazminogen'),
       ('G', 'Badania układu krzepnięcia', 'G81', 'Prekalikreina'),
       ('G', 'Badania układu krzepnięcia', 'G83', 'Tkankowy aktywator plazminogenu (TPA)'),
       ('G', 'Badania układu krzepnięcia', 'G85', 'Tromboelastogram'),
       ('I', 'Chemia kliniczna 1', 'I01', 'Acetooctan'),
       ('I', 'Chemia kliniczna 1', 'I02', 'Acylokarnityny'),
       ('I', 'Chemia kliniczna 1', 'I03', 'Acylotransferaza lecytyna-cholesterol (LCAT)'),
       ('I', 'Chemia kliniczna 1', 'I05', 'Adrenalina'),
       ('I', 'Chemia kliniczna 1', 'I07', 'Aktywność reninowa osocza (ARO)'),
       ('I', 'Chemia kliniczna 1', 'I09', 'Albumina'),
       ('I', 'Chemia kliniczna 1', 'I11', 'Albumina glikowana'),
       ('I', 'Chemia kliniczna 1', 'I13', 'Aldolaza'),
       ('I', 'Chemia kliniczna 1', 'I15', 'Aldosteron'),
       ('I', 'Chemia kliniczna 1', 'I16', 'Aminokwasy'),
       ('I', 'Chemia kliniczna 1', 'I17', 'Aminotransferaza alaninowa (ALT)'),
       ('I', 'Chemia kliniczna 1', 'I19', 'Aminotransferaza asparaginianowa (AST)'),
       ('I', 'Chemia kliniczna 1', 'I21', 'Aminotransferaza asparaginianowa mitochondrialna'),
       ('I', 'Chemia kliniczna 1', 'I23', 'Amoniak'),
       ('I', 'Chemia kliniczna 1', 'I25', 'Amylaza'),
       ('I', 'Chemia kliniczna 1', 'I27', 'Amylaza trzustkowa'),
       ('I', 'Chemia kliniczna 1', 'I29', 'Amyloid'),
       ('I', 'Chemia kliniczna 1', 'I31', 'Androstendion'),
       ('I', 'Chemia kliniczna 1', 'I33', 'Androsteron'),
       ('I', 'Chemia kliniczna 1', 'I34', 'Angiotensyna I'),
       ('I', 'Chemia kliniczna 1', 'I35', 'Angiotensyna II'),
       ('I', 'Chemia kliniczna 1', 'I37', 'Anhydraza węglanowa'),
       ('I', 'Chemia kliniczna 1', 'I39', '?-1-Antychymotrypsyna (ACT)'),
       ('I', 'Chemia kliniczna 1', 'I41', 'Antygen CA 125 (CA125)'),
       ('I', 'Chemia kliniczna 1', 'I43', 'Antygen CA 15-3 (CA15-3)'),
       ('I', 'Chemia kliniczna 1', 'I45', 'Antygen CA 19-9 (CA19-9)'),
       ('I', 'Chemia kliniczna 1', 'I47', 'Antygen CA 549'),
       ('I', 'Chemia kliniczna 1', 'I49', 'Antygen CA 72-4 (CA72-4)'),
       ('I', 'Chemia kliniczna 1', 'I51', 'Antygen CYFRA 21-1'),
       ('I', 'Chemia kliniczna 1', 'I52', 'Antygen nowotworowy HE4'),
       ('I', 'Chemia kliniczna 1', 'I53', 'Antygen karcynoembrionalny (CEA)'),
       ('I', 'Chemia kliniczna 1', 'I55', 'Antygen polipeptydowy (TPA)'),
       ('I', 'Chemia kliniczna 1', 'I57', 'Antygen polipeptydowy swoisty (TPS)'),
       ('I', 'Chemia kliniczna 1', 'I59', 'Antygen raka płaskonabłonkowego (SCC)'),
       ('I', 'Chemia kliniczna 1', 'I61', 'Antygen swoisty dla stercza (PSA) całkowity'),
       ('I', 'Chemia kliniczna 1', 'I63', 'Antygen swoisty dla stercza (PSA) wolny'),
       ('I', 'Chemia kliniczna 1', 'I65', '?-1-Antytrypsyna'),
       ('I', 'Chemia kliniczna 1', 'I67', 'Apolipoproteina B'),
       ('I', 'Chemia kliniczna 1', 'I69', 'Apolipoproteina E, izotypy'),
       ('I', 'Chemia kliniczna 1', 'I71', 'Apolipoproteina AI'),
       ('I', 'Chemia kliniczna 1', 'I73', 'Apolipoproteina AII'),
       ('I', 'Chemia kliniczna 1', 'I74', 'Apolipoproteina E, fenotyp'),
       ('I', 'Chemia kliniczna 1', 'I75', 'Arginaza'),
       ('I', 'Chemia kliniczna 1', 'I77', 'Białko całkowite'),
       ('I', 'Chemia kliniczna 1', 'I79', 'Białko całkowite, rozdział elektroforetyczny'),
       ('I', 'Chemia kliniczna 1', 'I81', 'Białko C-reaktywne (CRP)'),
       ('I', 'Chemia kliniczna 1', 'I82', 'Białko S-100'),
       ('I', 'Chemia kliniczna 1', 'I83', 'Białko wiążące hormony płciowe (SHBP)'),
       ('I', 'Chemia kliniczna 1', 'I84', 'Białko PAPP-A – osoczowe białko ciążowe A'),
       ('I', 'Chemia kliniczna 1', 'I85', 'Białko wiążące retinol (RBP)'),
       ('I', 'Chemia kliniczna 1', 'I86', 'Białko – immunofiksacja'),
       ('I', 'Chemia kliniczna 1', 'I87', 'Bilirubina bezpośrednia'),
       ('I', 'Chemia kliniczna 1', 'I89', 'Bilirubina całkowita'),
       ('I', 'Chemia kliniczna 1', 'I90', 'Bilirubina delta'),
       ('I', 'Chemia kliniczna 1', 'I91', 'Bilirubina pośrednia'),
       ('I', 'Chemia kliniczna 1', 'I93', 'Biotynidaza'),
       ('I', 'Chemia kliniczna 1', 'I95', 'Ceruloplazmina'),
       ('I', 'Chemia kliniczna 1', 'I97', 'Chlorek(Cl)'),
       ('I', 'Chemia kliniczna 1', 'I99', 'Cholesterol całkowity'),
       ('J', 'Badania immunohematologiczne', 'J41', 'HLA B27'),
       ('K', 'Chemia kliniczna 2', 'K01', 'Cholesterol HDL'),
       ('K', 'Chemia kliniczna 2', 'K02', 'Chitotriozydaza'),
       ('K', 'Chemia kliniczna 2', 'K03', 'Cholesterol LDL'),
       ('K', 'Chemia kliniczna 2', 'K04', 'Cukry proste'),
       ('K', 'Chemia kliniczna 2', 'K05', 'Cholesterol wolny'),
       ('K', 'Chemia kliniczna 2', 'K07', 'Cholesterol, estry'),
       ('K', 'Chemia kliniczna 2', 'K09', 'Chymotrypsyna'),
       ('K', 'Chemia kliniczna 2', 'K11', 'CO<MV>2 całkowity'),
       ('K', 'Chemia kliniczna 2', 'K12', 'CRF (czynnik uwaniający kortykotropinę)'),
       ('K', 'Chemia kliniczna 2', 'K13', 'Cykliczny AMP (cAMP)'),
       ('K', 'Chemia kliniczna 2', 'K15', 'Cynk (Zn)'),
       ('K', 'Chemia kliniczna 2', 'K16', 'Cystatyna C'),
       ('K', 'Chemia kliniczna 2', 'K17', 'Cysteina'),
       ('K', 'Chemia kliniczna 2', 'K19', 'Cystyna'),
       ('K', 'Chemia kliniczna 2', 'K21', 'Czynnik reumatoidalny (RF)'),
       ('K', 'Chemia kliniczna 2', 'K23', 'Dehydrataza ?-aminolewulinianu'),
       ('K', 'Chemia kliniczna 2', 'K25', 'Dehydroepiandrosteron niezwiązany (DHEA)'),
       ('K', 'Chemia kliniczna 2', 'K27', 'Dehydroepiandrosteronu siarczan (DHEAS)'),
       ('K', 'Chemia kliniczna 2', 'K29', 'Dehydrogenaza glukozo-6-fosforanu (G6PDH)'),
       ('K', 'Chemia kliniczna 2', 'K30', 'D-/L- arabinitol'),
       ('K', 'Chemia kliniczna 2', 'K31', 'Dehydrogenaza glutaminianowa (GLDH)'),
       ('K', 'Chemia kliniczna 2', 'K33', 'Dehydrogenaza mleczanowa (LDH)'),
       ('K', 'Chemia kliniczna 2', 'K35', 'Dehydrogenaza mleczanowa, izoenzymy'),
       ('K', 'Chemia kliniczna 2', 'K45', 'Dehydrogenaza ?-hydroksymaślanowa (HBDH)'),
       ('K', 'Chemia kliniczna 2', 'K47', 'Dekarboksylaza uroporfirynogenu'),
       ('K', 'Chemia kliniczna 2', 'K49', '11-Dezoksykortykotestosteron (DOC)'),
       ('K', 'Chemia kliniczna 2', 'K51', '11-Dezoksykortyzol'),
       ('K', 'Chemia kliniczna 2', 'K53', 'Dezoksypirydynolina (DPD)'),
       ('K', 'Chemia kliniczna 2', 'K55', 'Dihydrotestosteron'),
       ('K', 'Chemia kliniczna 2', 'K58', 'Dopełniacz (całkowita aktywność, CH50)'),
       ('K', 'Chemia kliniczna 2', 'K59', 'Dopełniacz, czynnik B'),
       ('K', 'Chemia kliniczna 2', 'K61', 'Dopełniacz, czynnik D'),
       ('K', 'Chemia kliniczna 2', 'K63', 'Dopełniacz, czynnik H'),
       ('K', 'Chemia kliniczna 2', 'K65', 'Dopełniacz, czynnik P'),
       ('K', 'Chemia kliniczna 2', 'K67', 'Dopełniacz, składowa C1q'),
       ('K', 'Chemia kliniczna 2', 'K69', 'Dopełniacz, składowa C1r'),
       ('K', 'Chemia kliniczna 2', 'K71', 'Dopełniacz, składowa C1s'),
       ('K', 'Chemia kliniczna 2', 'K73', 'Dopełniacz, składowa C2'),
       ('K', 'Chemia kliniczna 2', 'K75', 'Dopełniacz, składowa C3'),
       ('K', 'Chemia kliniczna 2', 'K77', 'Dopełniacz, składowa C4'),
       ('K', 'Chemia kliniczna 2', 'K79', 'Dopełniacz, składowa C5'),
       ('K', 'Chemia kliniczna 2', 'K81', 'Elastaza neutrofilowa'),
       ('K', 'Chemia kliniczna 2', 'K83', 'Elastaza trzustkowa'),
       ('K', 'Chemia kliniczna 2', 'K85', 'Enolaza neuronowa swoista'),
       ('K', 'Chemia kliniczna 2', 'K87', '?-Endorfina'),
       ('K', 'Chemia kliniczna 2', 'K89', 'Enzym konwertujący angiotensynę (ACE)'),
       ('K', 'Chemia kliniczna 2', 'K91', 'Erytropoetyna (EPO)'),
       ('K', 'Chemia kliniczna 2', 'K93', 'Esteraza acetylocholinowa'),
       ('K', 'Chemia kliniczna 2', 'K95', 'Esteraza cholinowa surowicy(pseudocholinesteraza)'),
       ('K', 'Chemia kliniczna 2', 'K97', 'Esterazy nieswoiste'),
       ('K', 'Chemia kliniczna 2', 'K99', 'Estradiol'),
       ('L', 'Chemia kliniczna 3', 'L01', 'Estriol'),
       ('L', 'Chemia kliniczna 3', 'L03', 'Fenyloalanina'),
       ('L', 'Chemia kliniczna 3', 'L05', 'Ferrytyna'),
       ('L', 'Chemia kliniczna 3', 'L07', '?-fetoproteina (AFP)'),
       ('L', 'Chemia kliniczna 3', 'L08', 'Fibronektyna'),
       ('L', 'Chemia kliniczna 3', 'L09', 'Fluorek (F)'),
       ('L', 'Chemia kliniczna 3', 'L11', 'Fosfataza alkaliczna'),
       ('L', 'Chemia kliniczna 3', 'L13', 'Fosfataza alkaliczna izoenzym kostny'),
       ('L', 'Chemia kliniczna 3', 'L15', 'Fosfataza kwaśna całkowita'),
       ('L', 'Chemia kliniczna 3', 'L16', 'Fosfataza kwaśna oporna na winian (TRAP)'),
       ('L', 'Chemia kliniczna 3', 'L17', 'Fosfataza kwaśna sterczowa (PAP)'),
       ('L', 'Chemia kliniczna 3', 'L19', 'Fosfatydylogliceryna'),
       ('L', 'Chemia kliniczna 3', 'L21', 'Fosfolipidy całkowite'),
       ('L', 'Chemia kliniczna 3', 'L23', 'Fosforan nieorganiczny'),
       ('L', 'Chemia kliniczna 3', 'L25', 'Fruktoza'),
       ('L', 'Chemia kliniczna 3', 'L27', 'Fruktozamina'),
       ('L', 'Chemia kliniczna 3', 'L28', 'Glikozaminoglikany'),
       ('L', 'Chemia kliniczna 3', 'L29', 'Galaktoza'),
       ('L', 'Chemia kliniczna 3', 'L31', 'Gamma glutamylotranspeptydaza (GGTP)'),
       ('L', 'Chemia kliniczna 3', 'L33', 'Gastryna'),
       ('L', 'Chemia kliniczna 3', 'L35', 'Glicerol wolny'),
       ('L', 'Chemia kliniczna 3', 'L37', 'Globulina wiążąca tyroksynę (TBG)'),
       ('L', 'Chemia kliniczna 3', 'L39', 'Globulina wiążąca witaminę D'),
       ('L', 'Chemia kliniczna 3', 'L41', 'Glukagon'),
       ('L', 'Chemia kliniczna 3', 'L43', 'Glukoza z krwi żylnej'),
       ('L', 'Chemia kliniczna 3', 'L45', 'Glutation zredukowany erytrocytów (GSH)'),
       ('L', 'Chemia kliniczna 3', 'L46', 'Gonadotropina kosmówkowa – podjednostka beta (?-HCG) '),
       ('L', 'Chemia kliniczna 3', 'L47', 'Gonadotropina kosmówkowa (HCG)'),
       ('L', 'Chemia kliniczna 3', 'L55', 'Hemoglobina glikowana (HbA1c)'),
       ('L', 'Chemia kliniczna 3', 'L57', 'Hemoglobina wolna'),
       ('L', 'Chemia kliniczna 3', 'L59', 'Hemopeksyna'),
       ('L', 'Chemia kliniczna 3', 'L62', 'Homocysteina'),
       ('L', 'Chemia kliniczna 3', 'L63', 'Hormon adrenokortykotropowy (ACTH)'),
       ('L', 'Chemia kliniczna 3', 'L65', 'Hormon folikulotropowy (FSH)'),
       ('L', 'Chemia kliniczna 3', 'L67', 'Hormon luteinizujący (LH)'),
       ('L', 'Chemia kliniczna 3', 'L69', 'Hormon tyreotropowy (TSH)'),
       ('L', 'Chemia kliniczna 3', 'L71', 'Hormon wzrostu (GH)'),
       ('L', 'Chemia kliniczna 3', 'L73', '17-Hydroksykorykosteroidy, całkowite (17-OHCS)'),
       ('L', 'Chemia kliniczna 3', 'L75', '18-Hydroksydezoksykortykosteron'),
       ('L', 'Chemia kliniczna 3', 'L77', '18- Hydroksykortykosteron'),
       ('L', 'Chemia kliniczna 3', 'L79', '17-Hydroksyprogesteron'),
       ('L', 'Chemia kliniczna 3', 'L81', '17-Hydroksypregnenolon'),
       ('L', 'Chemia kliniczna 3', 'L83', 'Hydroksyprolina'),
       ('L', 'Chemia kliniczna 3', 'L85', 'Immunoglobuliny A (IgA)'),
       ('L', 'Chemia kliniczna 3', 'L87', 'Immunoglobuliny D (IgD)'),
       ('L', 'Chemia kliniczna 3', 'L89', 'Immunoglobuliny E całkowite (IgE)'),
       ('L', 'Chemia kliniczna 3', 'L91', 'Immunoglobuliny E swoiste (IgE)'),
       ('L', 'Chemia kliniczna 3', 'L93', 'Immunoglobuliny G (IgG)'),
       ('L', 'Chemia kliniczna 3', 'L95', 'Immunoglobuliny M (IgM)'),
       ('L', 'Chemia kliniczna 3', 'L96', 'Inhibior C1-esterazy'),
       ('L', 'Chemia kliniczna 3', 'L97', 'Insulina'),
       ('L', 'Chemia kliniczna 3', 'L99', 'Interferon'),
       ('M', 'Chemia kliniczna 4', 'M01', 'Interleukina 1'),
       ('M', 'Chemia kliniczna 4', 'M03', 'Interleukina 2'),
       ('M', 'Chemia kliniczna 4', 'M05', 'Interleukina 6'),
       ('M', 'Chemia kliniczna 4', 'M06', 'Interleukina 8'),
       ('M', 'Chemia kliniczna 4', 'M07', 'Jod (J)'),
       ('M', 'Chemia kliniczna 4', 'M09', 'Kachektyna (TNF)'),
       ('M', 'Chemia kliniczna 4', 'M11', 'Kalcytonina'),
       ('M', 'Chemia kliniczna 4', 'M13', '?-karoten'),
       ('M', 'Chemia kliniczna 4', 'M15', 'Katecholaminy'),
       ('M', 'Chemia kliniczna 4', 'M17', '17-Ketosterydy, całkowite (17-KS)'),
       ('M', 'Chemia kliniczna 4', 'M18', 'Kinaza fosfokreatynowa (CK)'),
       ('M', 'Chemia kliniczna 4', 'M19', 'Kinaza fosfokreatynowa izoenzym CK-MB (CKMB)'),
       ('M', 'Chemia kliniczna 4', 'M21', 'Kinaza fosfokreatynowa, izoenzymy'),
       ('M', 'Chemia kliniczna 4', 'M22', 'Kinaza glicerolowa'),
       ('M', 'Chemia kliniczna 4', 'M23', 'Kinaza fosfokreatynowa, izoformy'),
       ('M', 'Chemia kliniczna 4', 'M25', 'Kobalt (Co)'),
       ('M', 'Chemia kliniczna 4', 'M27', 'Koproporfiryna'),
       ('M', 'Chemia kliniczna 4', 'M29', 'Kortykosteron'),
       ('M', 'Chemia kliniczna 4', 'M30', 'Kwas 3,7,11,15 – tetrametylo heksadekanowy (fitanowy)'),
       ('M', 'Chemia kliniczna 4', 'M31', 'Kortyzol'),
       ('M', 'Chemia kliniczna 4', 'M33', 'Kortyzol wolny'),
       ('M', 'Chemia kliniczna 4', 'M34', 'Kortykoidy wolne'),
       ('M', 'Chemia kliniczna 4', 'M35', 'Kreatyna'),
       ('M', 'Chemia kliniczna 4', 'M37', 'Kreatynina'),
       ('M', 'Chemia kliniczna 4', 'M38', 'Ksyloza'),
       ('M', 'Chemia kliniczna 4', 'M39', 'Kwas 5-hydroksy-indolooctowy (5-HIAA)'),
       ('M', 'Chemia kliniczna 4', 'M41', 'Kwas foliowy'),
       ('M', 'Chemia kliniczna 4', 'M43', 'Kwas homowanilinowy (HVA)'),
       ('M', 'Chemia kliniczna 4', 'M45', 'Kwas moczowy'),
       ('M', 'Chemia kliniczna 4', 'M47', 'Kwas wanilinomigdałowy (VMA)'),
       ('M', 'Chemia kliniczna 4', 'M49', 'Kwas ?-hydroksymasłowy'),
       ('M', 'Chemia kliniczna 4', 'M51', 'Kwas ?-aminolewulinowy (ALA)'),
       ('M', 'Chemia kliniczna 4', 'M52', 'Kwas p-aminobenzoesowy (PABA)'),
       ('M', 'Chemia kliniczna 4', 'M53', 'Kwasy żółciowe'),
       ('M', 'Chemia kliniczna 4', 'M55', 'Kwaśność miareczkowa'),
       ('M', 'Chemia kliniczna 4', 'M57', 'Laktogen łożyskowy'),
       ('M', 'Chemia kliniczna 4', 'M59', 'Laktoza'),
       ('M', 'Chemia kliniczna 4', 'M61', 'Lecytyna'),
       ('M', 'Chemia kliniczna 4', 'M62', 'Leptyna'),
       ('M', 'Chemia kliniczna 4', 'M63', 'Leucyloaminopeptydaza (LAP)'),
       ('M', 'Chemia kliniczna 4', 'M65', 'Leucyna'),
       ('M', 'Chemia kliniczna 4', 'M67', 'Lipaza'),
       ('M', 'Chemia kliniczna 4', 'M69', 'Lipoproteina a [Lp(a)]'),
       ('M', 'Chemia kliniczna 4', 'M71', 'Lipoproteiny/lipidy, rozdział'),
       ('M', 'Chemia kliniczna 4', 'M73', 'Lit (Li)'),
       ('M', 'Chemia kliniczna 4', 'M75', 'Lizozym (muramidaza)'),
       ('M', 'Chemia kliniczna 4', 'M76', 'L-karnityna całkowita'),
       ('M', 'Chemia kliniczna 4', 'M77', 'Luka anionowa'),
       ('M', 'Chemia kliniczna 4', 'M78', 'L-karnityna wolna'),
       ('M', 'Chemia kliniczna 4', 'M79', 'Luka osmotyczna'),
       ('M', 'Chemia kliniczna 4', 'M81', 'Łańcuchy ciężkie'),
       ('M', 'Chemia kliniczna 4', 'M82', 'Kwasy tłuszczowe bardzo długołańcuchowe (VLCFA)'),
       ('M', 'Chemia kliniczna 4', 'M83', 'Łańcuchy lekkie kappa'),
       ('M', 'Chemia kliniczna 4', 'M85', 'Łańcuchy lekkie lambda'),
       ('M', 'Chemia kliniczna 4', 'M87', 'Magnez całkowity (Mg)'),
       ('M', 'Chemia kliniczna 4', 'M89', 'Magnez zjonizowany (Mg<M^>++)'),
       ('M', 'Chemia kliniczna 4', 'M91', '?-2-Makroglobulina'),
       ('M', 'Chemia kliniczna 4', 'M92', '?2-mikroglobulina'),
       ('M', 'Chemia kliniczna 4', 'M93', 'Mangan (Mn)'),
       ('M', 'Chemia kliniczna 4', 'M95', 'Metionina'),
       ('M', 'Chemia kliniczna 4', 'M97', 'Metoksyadrenalina'),
       ('M', 'Chemia kliniczna 4', 'M99', 'Metoksykatecholaminy całkowite'),
       ('N', 'Chemia kliniczna 5', 'N01', 'Metoksynoradrenalina'),
       ('N', 'Chemia kliniczna 5', 'N11', 'Mleczan'),
       ('N', 'Chemia kliniczna 5', 'N13', 'Mocznik'),
       ('N', 'Chemia kliniczna 5', 'N15', 'Molibden (Mo)'),
       ('N', 'Chemia kliniczna 5', 'N17', 'N-Acetyloglukozaminidaza (NAG)'),
       ('N', 'Chemia kliniczna 5', 'N19', 'Neopteryna'),
       ('N', 'Chemia kliniczna 5', 'N21', 'Noradrenalina'),
       ('N', 'Chemia kliniczna 5', 'N22', 'NT-proANP'),
       ('N', 'Chemia kliniczna 5', 'N23', '5''-Nukleotydaza'),
       ('N', 'Chemia kliniczna 5', 'N24', 'NT-proBNP'),
       ('N', 'Chemia kliniczna 5', 'N25', 'Osmolarność'),
       ('N', 'Chemia kliniczna 5', 'N26', 'Orozomukoid'),
       ('N', 'Chemia kliniczna 5', 'N27', 'Osteokalcyna'),
       ('N', 'Chemia kliniczna 5', 'N29', 'Parathormon (PTH)'),
       ('N', 'Chemia kliniczna 5', 'N30', 'Parathormon intact (iPTH)'),
       ('N', 'Chemia kliniczna 5', 'N33', 'Peptyd C'),
       ('N', 'Chemia kliniczna 5', 'N34', 'Peptyd natriuretyczny typu B (BNP)'),
       ('N', 'Chemia kliniczna 5', 'N35', 'Peroksydaza glutationowa'),
       ('N', 'Chemia kliniczna 5', 'N37', 'Pirogronian'),
       ('N', 'Chemia kliniczna 5', 'N39', 'Pirydynolina (PYD)'),
       ('N', 'Chemia kliniczna 5', 'N40', 'Podjednostka ? hormonów glikoproteidowych'),
       ('N', 'Chemia kliniczna 5', 'N41', 'Porfiryny całkowite'),
       ('N', 'Chemia kliniczna 5', 'N42', 'Karboksyporfiryny'),
       ('N', 'Chemia kliniczna 5', 'N43', 'Porfobilinogen'),
       ('N', 'Chemia kliniczna 5', 'N44', 'Oligosacharydy'),
       ('N', 'Chemia kliniczna 5', 'N45', 'Potas (K)'),
       ('N', 'Chemia kliniczna 5', 'N47', 'Prealbumina'),
       ('N', 'Chemia kliniczna 5', 'N49', 'Pregnandiol'),
       ('N', 'Chemia kliniczna 5', 'N50', 'Palmitoilotransferaza karnitynowa IiII (CPT I i CPT II)'),
       ('N', 'Chemia kliniczna 5', 'N51', 'Pregnantriol'),
       ('N', 'Chemia kliniczna 5', 'N53', 'Pregnenolon'),
       ('N', 'Chemia kliniczna 5', 'N55', 'Progesteron'),
       ('N', 'Chemia kliniczna 5', 'N57', 'Proinsulina'),
       ('N', 'Chemia kliniczna 5', 'N58', 'Prokalcytonina'),
       ('N', 'Chemia kliniczna 5', 'N59', 'Prolaktyna'),
       ('N', 'Chemia kliniczna 5', 'N60', 'Protoporfiryna cynkowa'),
       ('N', 'Chemia kliniczna 5', 'N61', 'Protoporfiryny'),
       ('N', 'Chemia kliniczna 5', 'N63', 'Przeciwciała przeciw antygenom nadnerczy'),
       ('N', 'Chemia kliniczna 5', 'N65', 'Przeciwciała przeciw antygenom przytarczyc'),
       ('N', 'Chemia kliniczna 5', 'N66', 'Przeciwciała przeciw białkom bogatym w cytrulinę (CCP)'),
       ('N', 'Chemia kliniczna 5', 'N67', 'Przeciwciała przeciw błonie podstawnej kłębków nerkowych (anty-GMB)'),
       ('N', 'Chemia kliniczna 5', 'N69', 'Przeciwciała przeciw cytoplazmie (ANCA)'),
       ('N', 'Chemia kliniczna 5', 'N71', 'Przeciwciała przeciw czynnikowi wewnętrznemu Castle''a (IFA)'),
       ('N', 'Chemia kliniczna 5', 'N73', 'Przeciwciała przeciw desmogleinie'),
       ('N', 'Chemia kliniczna 5', 'N75', 'Przeciwciała przeciw DNA dwuniciowemu (dsDNA)'),
       ('N', 'Chemia kliniczna 5', 'N77', 'Przeciwciała przeciw DNA jednoniciowemu (ssDNA)'),
       ('N', 'Chemia kliniczna 5', 'N79', 'Przeciwciała przeciw endomysium'),
       ('N', 'Chemia kliniczna 5', 'N81', 'Przeciwciała przeciw gliadynie klasy IgG'),
       ('N', 'Chemia kliniczna 5', 'N83', 'Przeciwciała przeciw gliadynie, klasy IgA'),
       ('N', 'Chemia kliniczna 5', 'N85', 'Przeciwciała przeciw histonom'),
       ('N', 'Chemia kliniczna 5', 'N87', 'Przeciwciała przeciw insulinie'),
       ('N', 'Chemia kliniczna 5', 'N89', 'Przeciwciała przeciw kardiolipinie'),
       ('N', 'Chemia kliniczna 5', 'N91', 'Przeciwciała przeciw komórkom mięśni gładkich'),
       ('N', 'Chemia kliniczna 5', 'N93', 'Przeciwciała przeciw komórkom mięśni szkieletowych'),
       ('N', 'Chemia kliniczna 5', 'N95', 'Przeciwciała przeciw komórkom mięśnia sercowego'),
       ('N', 'Chemia kliniczna 5', 'N97', 'Przeciwciała przeciw komórkom okładzinowym żołądka'),
       ('N', 'Chemia kliniczna 5', 'N99', 'Przeciwciała przeciw komórkom wysp trzustki'),
       ('O', 'Chemia kliniczna 6', 'O01', 'Przeciwciała przeciw limfocytom'),
       ('O', 'Chemia kliniczna 6', 'O03', 'Przeciwciała przeciw mielinie'),
       ('O', 'Chemia kliniczna 6', 'O05', 'Przeciwciała przeciw mitochondriom'),
       ('O', 'Chemia kliniczna 6', 'O07', 'Przeciwciała przeciw neutrofilom'),
       ('O', 'Chemia kliniczna 6', 'O09', 'Przeciwciała przeciw peroksydazie tarczycowej'),
       ('O', 'Chemia kliniczna 6', 'O11', 'Przeciwciała przeciw płytkom krwi'),
       ('O', 'Chemia kliniczna 6', 'O12', 'Identyfikacja alloprzeciwciał'),
       ('O', 'Chemia kliniczna 6', 'O13', 'Przeciwciała przeciw receptorowi insuliny'),
       ('O', 'Chemia kliniczna 6', 'O15', 'Przeciwciała przeciw receptorowi tyreotropiny'),
       ('O', 'Chemia kliniczna 6', 'O17', 'Przeciwciała przeciw retikulinie'),
       ('O', 'Chemia kliniczna 6', 'O18', 'Przeciwciała przeciw tyreoglobulinie'),
       ('O', 'Chemia kliniczna 6', 'O19', 'Przeciwciała przeciw tyreotropinie'),
       ('O', 'Chemia kliniczna 6', 'O21', 'Przeciwciała przeciwjądrowe (ANA)'),
       ('O', 'Chemia kliniczna 6', 'O22', 'Przedsionkowy peptyd natriuretyczny (ANP)'),
       ('O', 'Chemia kliniczna 6', 'O23', 'Receptory hormonów sterydowych'),
       ('O', 'Chemia kliniczna 6', 'O24', 'Receptor IL2'),
       ('O', 'Chemia kliniczna 6', 'O25', 'Reduktaza glutationu'),
       ('O', 'Chemia kliniczna 6', 'O26', 'Receptor IL6'),
       ('O', 'Chemia kliniczna 6', 'O27', 'Renina'),
       ('O', 'Chemia kliniczna 6', 'O28', 'Rozpuszczalny receptor transferyny (sTfR)'),
       ('O', 'Chemia kliniczna 6', 'O29', 'Równowaga kwasowo-zasadowa (pH, pCO2, pO2, HCO3, BE)'),
       ('O', 'Chemia kliniczna 6', 'O31', 'Selen (Se)'),
       ('O', 'Chemia kliniczna 6', 'O32', 'Somatomedyna C (IGF-1)'),
       ('O', 'Chemia kliniczna 6', 'O33', 'Serotonina'),
       ('O', 'Chemia kliniczna 6', 'O34', 'Rybonukleozyd 5-aminoimidazolo-4-N-bursztynylokarboksyamidowy (SAICAr)'),
       ('O', 'Chemia kliniczna 6', 'O35', 'Sód (Na)'),
       ('O', 'Chemia kliniczna 6', 'O37', 'Syntaza uroporfirynogenu'),
       ('O', 'Chemia kliniczna 6', 'O39', 'Szczawian'),
       ('O', 'Chemia kliniczna 6', 'O41', 'Testosteron'),
       ('O', 'Chemia kliniczna 6', 'O43', 'Transferyna'),
       ('O', 'Chemia kliniczna 6', 'O45', 'Transferyna, wskaźnik nasycenia żelazem'),
       ('O', 'Chemia kliniczna 6', 'O47', 'Transferyna z niedoborem węglowodanów (CDT)'),
       ('O', 'Chemia kliniczna 6', 'O48', 'Transferyna, izoformy'),
       ('O', 'Chemia kliniczna 6', 'O49', 'Triglicerydy'),
       ('O', 'Chemia kliniczna 6', 'O51', 'Trijodotyronina całkowita (TT3)'),
       ('O', 'Chemia kliniczna 6', 'O52', 'Siarczyny'),
       ('O', 'Chemia kliniczna 6', 'O53', 'Trijodotyronina odwrotna (rT3)'),
       ('O', 'Chemia kliniczna 6', 'O54', 'Sjalooligosacharydy'),
       ('O', 'Chemia kliniczna 6', 'O55', 'Trijodotyronina wolna (FT3)'),
       ('O', 'Chemia kliniczna 6', 'O59', 'Troponina I'),
       ('O', 'Chemia kliniczna 6', 'O61', 'Troponina T'),
       ('O', 'Chemia kliniczna 6', 'O62', 'Kwasy organiczne'),
       ('O', 'Chemia kliniczna 6', 'O63', 'Trypsyna'),
       ('O', 'Chemia kliniczna 6', 'O65', 'Tyreoglobulina'),
       ('O', 'Chemia kliniczna 6', 'O66', 'Kwas orotowy'),
       ('O', 'Chemia kliniczna 6', 'O67', 'Tyroksyna całkowita (TT4)'),
       ('O', 'Chemia kliniczna 6', 'O69', 'Tyroksyna wolna (FT4)'),
       ('O', 'Chemia kliniczna 6', 'O73', 'Uroporfiryny'),
       ('O', 'Chemia kliniczna 6', 'O74', 'Urydylotransferaza galaktozo – 1 fosforanowa (GALT)'),
       ('O', 'Chemia kliniczna 6', 'O75', 'Wapń zjonizowany (Ca2+)'),
       ('O', 'Chemia kliniczna 6', 'O77', 'Wapń całkowity (Ca)'),
       ('O', 'Chemia kliniczna 6', 'O79', 'Wazopresyna (ADH)'),
       ('O', 'Chemia kliniczna 6', 'O81', 'Witamina A'),
       ('O', 'Chemia kliniczna 6', 'O83', 'Witamina B12'),
       ('O', 'Chemia kliniczna 6', 'O85', 'Witamina C (kwas askorbinowy)'),
       ('O', 'Chemia kliniczna 6', 'O87', 'Witamina D - 1, 25 OH'),
       ('O', 'Chemia kliniczna 6', 'O89', 'Witamina D - 24, 25 OH'),
       ('O', 'Chemia kliniczna 6', 'O91', 'Witamina D - 25 OH'),
       ('O', 'Chemia kliniczna 6', 'O92', 'Wolne kwasy tłuszczowe'),
       ('O', 'Chemia kliniczna 6', 'O93', 'Żelazo - całkowita zdolność wiązania (TIBC)'),
       ('O', 'Chemia kliniczna 6', 'O95', 'Żelazo (Fe)'),
       ('P', 'Toksykologia 1', 'P01', '1-hydroksypiren'),
       ('P', 'Toksykologia 1', 'P03', '2,5-heksanodion'),
       ('P', 'Toksykologia 1', 'P05', 'Alkaloidy opium'),
       ('P', 'Toksykologia 1', 'P07', 'Amfetamina'),
       ('P', 'Toksykologia 1', 'P09', 'Aminopiryna'),
       ('P', 'Toksykologia 1', 'P11', 'Arsen'),
       ('P', 'Toksykologia 1', 'P13', 'Barbiturany'),
       ('P', 'Toksykologia 1', 'P15', 'Benzen'),
       ('P', 'Toksykologia 1', 'P17', 'Benzoesowy kwas'),
       ('P', 'Toksykologia 1', 'P19', 'Chrom (Cr)'),
       ('P', 'Toksykologia 1', 'P21', 'Diazepam'),
       ('P', 'Toksykologia 1', 'P23', 'Disulfiram'),
       ('P', 'Toksykologia 1', 'P25', 'Dwufenylohydantoina'),
       ('P', 'Toksykologia 1', 'P27', 'Etylenowy glikol'),
       ('P', 'Toksykologia 1', 'P29', 'Etylobenzen'),
       ('P', 'Toksykologia 1', 'P31', 'Etylowy alkohol'),
       ('P', 'Toksykologia 1', 'P33', 'Fenol'),
       ('P', 'Toksykologia 1', 'P37', 'Glimid'),
       ('P', 'Toksykologia 1', 'P39', 'Glin'),
       ('P', 'Toksykologia 1', 'P41', 'Hemoglobina tlenkowęglowa'),
       ('P', 'Toksykologia 1', 'P43', 'Kadm (Cd)'),
       ('P', 'Toksykologia 1', 'P44', 'Kanabinoidy'),
       ('P', 'Toksykologia 1', 'P45', 'Kokaina'),
       ('P', 'Toksykologia 1', 'P47', 'Ksylen'),
       ('P', 'Toksykologia 1', 'P49', 'Leki'),
       ('P', 'Toksykologia 1', 'P51', 'Lotne związki organiczne'),
       ('P', 'Toksykologia 1', 'P55', 'Meprobamat'),
       ('P', 'Toksykologia 1', 'P57', 'Metadon'),
       ('P', 'Toksykologia 1', 'P59', 'Metakwalon'),
       ('P', 'Toksykologia 1', 'P60', 'Metamfetamina'),
       ('P', 'Toksykologia 1', 'P61', 'Methemoglobina (MetHb)'),
       ('P', 'Toksykologia 1', 'P63', 'Metylohipurowy alkohol'),
       ('P', 'Toksykologia 1', 'P65', 'Metylowy alkohol'),
       ('P', 'Toksykologia 1', 'P67', 'Migdałowy kwas'),
       ('P', 'Toksykologia 1', 'P68', 'Morfina'),
       ('P', 'Toksykologia 1', 'P69', 'Nikiel (Ni)'),
       ('P', 'Toksykologia 1', 'P71', 'Ołów (Pb)'),
       ('P', 'Toksykologia 1', 'P73', 'p-aminofenol'),
       ('P', 'Toksykologia 1', 'P75', 'Paracetamol'),
       ('P', 'Toksykologia 1', 'P77', 'p-nitrofenol'),
       ('P', 'Toksykologia 1', 'P79', 'Pochodne benzodwuazepiny'),
       ('P', 'Toksykologia 1', 'P81', 'Pochodne fenotiazyny'),
       ('P', 'Toksykologia 1', 'P83', 'Polichlorowane bifenyle'),
       ('P', 'Toksykologia 1', 'P85', 'Propranolol'),
       ('P', 'Toksykologia 1', 'P89', 'Rtęć (Hg)'),
       ('P', 'Toksykologia 1', 'P91', 'Salicylany'),
       ('P', 'Toksykologia 1', 'P93', 'Styren'),
       ('P', 'Toksykologia 1', 'P95', 'Tal (Tl)'),
       ('P', 'Toksykologia 1', 'P97', 'Tetrachloroetylen'),
       ('P', 'Toksykologia 1', 'P99', 'Tetrahydrokanabinal'),
       ('Q', 'Chemia kliniczna 7', 'Q40', 'Palmitynian, utlenianie'),
       ('R', 'Toksykologia 2', 'R01', 'Toluen'),
       ('R', 'Toksykologia 2', 'R03', 'Trójchlorooctowy kwas'),
       ('R', 'Toksykologia 2', 'R05', 'Trójcykliczne antydepresanty'),
       ('R', 'Toksykologia 2', 'R07', 'Wanad (Ve)'),
       ('S', 'Bakteriologia', 'S01', 'Bacillus cereus Antygen enterotoksyny'),
       ('S', 'Bakteriologia', 'S03', 'Bacteroides fragilis DNA enterotoksyny (fragilizyny)'),
       ('S', 'Bakteriologia', 'S05', 'Bordetella pertussis Przeciwciała IgA'),
       ('S', 'Bakteriologia', 'S07', 'Bordetella pertussis Przeciwciała IgG'),
       ('S', 'Bakteriologia', 'S09', 'Bordetella pertussis Przeciwciała IgM'),
       ('S', 'Bakteriologia', 'S11', 'Bordetella pertussis Przeciwciała IgG/ IgM (anty-B. pertusis IgG/ IgM)'),
       ('S', 'Bakteriologia', 'S13', 'Bordetella pertussis IgA/ toksyna'),
       ('S', 'Bakteriologia', 'S15', 'Bordetella pertussis IgG/ toksyna'),
       ('S', 'Bakteriologia', 'S17', 'Bordetella pertussis IgM/ toksyna (anty-B.pertusis toksyna IgM)'),
       ('S', 'Bakteriologia', 'S19', 'Bordetella pertussis Przeciwciała IgG/ IgA (anty-B. pertusis toksyna IgG/ IgA)'),
       ('S', 'Bakteriologia', 'S21', 'Borrelia burgdorferi (Lyme) IgG Przeciwciała (anty-B.burgdorferi IgG)'),
       ('S', 'Bakteriologia', 'S23', 'Borrelia burgdorferi (Lyme) Przeciwciała IgG - test potwierdzający'),
       ('S', 'Bakteriologia', 'S25', 'Borrelia burgdorferi (Lyme) Przeciwciała IgM (anty-B.burgdorferi IgM)'),
       ('S', 'Bakteriologia', 'S27', 'Borrelia burgdorferi (Lyme) Przeciwciała IgM - test potwierdzający'),
       ('S', 'Bakteriologia', 'S29', 'Borrelia burgdorferi (Lyme) IgG/ IgM Przeciwciała (anty-B.burgdorferi IgG/ IgM)'),
       ('S', 'Bakteriologia', 'S31', 'Borrelia burgdorferi (Lyme) Przeciwciała IgG/ IgM - test potwierdzający'),
       ('S', 'Bakteriologia', 'S33', 'Borrelia afzelli Przeciwciała IgG'),
       ('S', 'Bakteriologia', 'S35', 'Borrelia afzelli Przeciwciała IgM'),
       ('S', 'Bakteriologia', 'S37', 'Borrelia Przeciwciała (całkowite)'),
       ('S', 'Bakteriologia', 'S39', 'Brucella Przeciwciała IgA (anty-Brucella IgA)'),
       ('S', 'Bakteriologia', 'S41', 'Brucella IgG Przeciwciała (anty-Brucella IgG)'),
       ('S', 'Bakteriologia', 'S43', 'Brucella Przeciwciała IgM (anty-Brucella IgM)'),
       ('S', 'Bakteriologia', 'S45', 'Brucella Przeciwciała (całkowite)'),
       ('S', 'Bakteriologia', 'S47', 'Ehrlichia Przeciwciała IgG Ia'),
       ('S', 'Bakteriologia', 'S49', 'Campylobacter Antygen (Campylobacter Antygen)'),
       ('S', 'Bakteriologia', 'S51', 'Campylobacter Przeciwciała IgG (anty-Campylobacter IgG)'),
       ('S', 'Bakteriologia', 'S53', 'Campylobacter Przeciwciała IgA (anty-Campylobacter IgA)'),
       ('S', 'Bakteriologia', 'S55', 'Campylobacter Przeciwciała IgM (anty-Campylobacter IgM)'),
       ('S', 'Bakteriologia', 'S59', 'Chlamydia Antygen (Chlamydia Antygen)'),
       ('S', 'Bakteriologia', 'S61', 'Chlamydia Przeciwciała IgG'),
       ('S', 'Bakteriologia', 'S63', 'Chlamydophila pneumoniae Przeciwciała IgA (anty-Ch. pneumoniae IgA)'),
       ('S', 'Bakteriologia', 'S65', 'Chlamydophila pneumoniae Przeciwciała IgM (anty-Ch. pneumoniae IgM)'),
       ('S', 'Bakteriologia', 'S67', 'Chlamydophila pneumoniae Przeciwciała IgG (anty-Ch. pneumoniae IgG)'),
       ('S', 'Bakteriologia', 'S69', 'Chlamydia trachomatis Antygen'),
       ('S', 'Bakteriologia', 'S71', 'Chlamydia trachomatis Przeciwciała IgA (anty-Ch. trachomatis IgA)'),
       ('S', 'Bakteriologia', 'S73', 'Chlamydia trachomatis Przeciwciała IgG (anty-Ch. trachomatis IgG)'),
       ('S', 'Bakteriologia', 'S75', 'Chlamydia trachomatis Przeciwciała IgM'),
       ('S', 'Bakteriologia', 'S77', 'Chlamydia trachomatis Przeciwciała IgG/ IgM'),
       ('S', 'Bakteriologia', 'S79', 'Chlamydia trachomatis DNA'),
       ('S', 'Bakteriologia', 'S80', 'Clostridium difficile Toksyna A/ Antygen'),
       ('S', 'Bakteriologia', 'S81', 'Clostridium difficile Antygen/ Toksyna A + B'),
       ('S', 'Bakteriologia', 'S82', 'Clostridium difficile Antygen'),
       ('S', 'Bakteriologia', 'S83', 'Clostridium difficile DNA toxyn A i B'),
       ('S', 'Bakteriologia', 'S84', 'Clostridium perfringens Antygen enterotoksyny'),
       ('S', 'Bakteriologia', 'S85', 'Clostridium tetani Przeciwciała IgG/ toksyna'),
       ('S', 'Bakteriologia', 'S86', 'Clostridium tetani Przeciwciała IgG/ toksyna (ilościowo)'),
       ('S', 'Bakteriologia', 'S87', 'Corynebacterium diphtheriae Przeciwciała IgG'),
       ('S', 'Bakteriologia', 'S88', 'Corynebacterium diphtheriae Przeciwciała IgG (anty-C.diphtheriae toksyna IgG)'),
       ('S', 'Bakteriologia', 'S89', 'Corynebacterium diphtheriae Przeciwciała IgG (anty-C.diphtheriae toksyna IgG) (ilościowo)'),
       ('S', 'Bakteriologia', 'S90', 'Coxiella burnetii (Gorączka Q) IgG'),
       ('S', 'Bakteriologia', 'S91', 'Coxiella burnetii IgA'),
       ('S', 'Bakteriologia', 'S92', 'Coxiella burnetii IgM'),
       ('S', 'Bakteriologia', 'S93', 'Escherichia coli O157 (EHEC) Antygen'),
       ('S', 'Bakteriologia', 'S94', 'Escherichia coli O157 (EHEC) Przeciwciała'),
       ('S', 'Bakteriologia', 'S95', 'Escherichia coli Antygen werotoksyny (VT1, VT2)'),
       ('S', 'Bakteriologia', 'S96', 'Escherichia coli (EPEC) Antygen (surowica poliwalentna)'),
       ('S', 'Bakteriologia', 'S97', 'Escherichia coli (EPEC) Antygen (surowica trójwalentna)'),
       ('S', 'Bakteriologia', 'S98', 'Escherichia coli (EPEC) Antygen (surowica monowalentna)'),
       ('S', 'Bakteriologia', 'S99', 'Escherichia coli Antygen enterotoksyna ciepłostabilna'),
       ('T', 'Monitorowanie stężenia leków', 'T01', 'Amikacyna'),
       ('T', 'Monitorowanie stężenia leków', 'T03', 'Amiodaron'),
       ('T', 'Monitorowanie stężenia leków', 'T05', 'Amitryptylina'),
       ('T', 'Monitorowanie stężenia leków', 'T07', 'Chinidyna'),
       ('T', 'Monitorowanie stężenia leków', 'T09', 'Chloramfenikol'),
       ('T', 'Monitorowanie stężenia leków', 'T11', 'Cyklosporyna A (CsA)'),
       ('T', 'Monitorowanie stężenia leków', 'T13', 'Dezypramina'),
       ('T', 'Monitorowanie stężenia leków', 'T15', 'Digitoksyna'),
       ('T', 'Monitorowanie stężenia leków', 'T17', 'Digoksyna'),
       ('T', 'Monitorowanie stężenia leków', 'T19', 'Doksepina'),
       ('T', 'Monitorowanie stężenia leków', 'T21', 'Dyzopyramid'),
       ('T', 'Monitorowanie stężenia leków', 'T23', 'Etosuksymid'),
       ('T', 'Monitorowanie stężenia leków', 'T25', 'Fenobarbital'),
       ('T', 'Monitorowanie stężenia leków', 'T27', 'Fenytoina'),
       ('T', 'Monitorowanie stężenia leków', 'T29', 'Flekainid'),
       ('T', 'Monitorowanie stężenia leków', 'T30', 'Gentamycyna'),
       ('T', 'Monitorowanie stężenia leków', 'T31', 'Imipramina'),
       ('T', 'Monitorowanie stężenia leków', 'T33', 'Karbamazepina'),
       ('T', 'Monitorowanie stężenia leków', 'T35', 'Klomipramina'),
       ('T', 'Monitorowanie stężenia leków', 'T37', 'Lidokaina'),
       ('T', 'Monitorowanie stężenia leków', 'T39', 'Meksyletyna'),
       ('T', 'Monitorowanie stężenia leków', 'T41', 'Metotreksat'),
       ('T', 'Monitorowanie stężenia leków', 'T43', 'N-acetylo-prokainamid (NAPA)'),
       ('T', 'Monitorowanie stężenia leków', 'T45', 'Netylmycyna'),
       ('T', 'Monitorowanie stężenia leków', 'T47', 'Nortryptylina'),
       ('T', 'Monitorowanie stężenia leków', 'T49', 'Prokainamid'),
       ('T', 'Monitorowanie stężenia leków', 'T51', 'Propafenon'),
       ('T', 'Monitorowanie stężenia leków', 'T53', 'Prymidon'),
       ('T', 'Monitorowanie stężenia leków', 'T54', 'Sirolimus'),
       ('T', 'Monitorowanie stężenia leków', 'T55', 'Teofilina'),
       ('T', 'Monitorowanie stężenia leków', 'T56', 'Takrolimus'),
       ('T', 'Monitorowanie stężenia leków', 'T57', 'Tobramycyna'),
       ('T', 'Monitorowanie stężenia leków', 'T59', 'Walproinowy kwas'),
       ('T', 'Monitorowanie stężenia leków', 'T61', 'Wankomycyna'),
       ('U', 'Bakteriologia 2', 'U01', 'Escherichia coli, Vibrio cholerae Antygen enterotoksyny ciepłochwiejne'),
       ('U', 'Bakteriologia 2', 'U02', 'Francisella tularensis Przeciwciała'),
       ('U', 'Bakteriologia 2', 'U03', 'Haemophilus influenzae (typ a,b,c,d,e,f) Antygen (surowice monowalente)'),
       ('U', 'Bakteriologia 2', 'U04', 'Haemophilus influenzae (typ b) Antygen'),
       ('U', 'Bakteriologia 2', 'U05', 'Haemophilus influenzae DNA'),
       ('U', 'Bakteriologia 2', 'U06', 'Helicobacter pylori Przeciwciała'),
       ('U', 'Bakteriologia 2', 'U07', 'Helicobacter pylori Przeciwciała IgA (anty-H.pylori IgA)'),
       ('U', 'Bakteriologia 2', 'U08', 'Helicobacter pylori Przeciwciała IgA - test potwierdzenia'),
       ('U', 'Bakteriologia 2', 'U09', 'Helicobacter pylori Przeciwciała IgA (ilościowy)'),
       ('U', 'Bakteriologia 2', 'U10', 'Helicobacter pylori IgG Przeciwciała (anty-H.pylori IgG)'),
       ('U', 'Bakteriologia 2', 'U11', 'Helicobacter pylori IgG Przeciwciała - test potwierdzenia'),
       ('U', 'Bakteriologia 2', 'U12', 'Helicobacter pylori IgG Przeciwciała (ilościowo)'),
       ('U', 'Bakteriologia 2', 'U13', 'Helicobacter pylori IgM Przeciwciała (ilościowo)'),
       ('U', 'Bakteriologia 2', 'U14', 'Helicobacter pylori IgG/ IgA Przeciwciała (anty-H. pylori IgG/ IgA)'),
       ('U', 'Bakteriologia 2', 'U15', 'Helicobacter pylori Antygen'),
       ('U', 'Bakteriologia 2', 'U16', 'Legionella pneumophila (1-7) Przeciwciała IgG'),
       ('U', 'Bakteriologia 2', 'U17', 'Legionella pneumophila (1-7) Przeciwciała IgM'),
       ('U', 'Bakteriologia 2', 'U18', 'Legionella pneumophila Antygen'),
       ('U', 'Bakteriologia 2', 'U19', 'Legionella pneumophila IgG/ IgM/ IgA'),
       ('U', 'Bakteriologia 2', 'U20', 'Legionella pneumophila Serogrupa 1 Antygen'),
       ('U', 'Bakteriologia 2', 'U21', 'Legionella pneumophila Serogrupa 2-14 Antygen'),
       ('U', 'Bakteriologia 2', 'U22', 'Legionella spp. Antygen'),
       ('U', 'Bakteriologia 2', 'U23', 'Leptospira Antygen'),
       ('U', 'Bakteriologia 2', 'U24', 'Leptospira Przeciwciała IgG'),
       ('U', 'Bakteriologia 2', 'U25', 'Leptospira Przeciwciała IgM'),
       ('U', 'Bakteriologia 2', 'U26', 'Listeria spp. Antygen'),
       ('U', 'Bakteriologia 2', 'U27', 'Listeria monocytogenes DNA'),
       ('U', 'Bakteriologia 2', 'U28', 'Mycobacterium avium DNA'),
       ('U', 'Bakteriologia 2', 'U29', 'Mycobacterium avium complex DNA'),
       ('U', 'Bakteriologia 2', 'U30', 'Mycobacterium kansasii DNA'),
       ('U', 'Bakteriologia 2', 'U31', 'Mycobacterium gordonae DNA'),
       ('U', 'Bakteriologia 2', 'U32', 'Mycobacterium intracellulare DNA'),
       ('U', 'Bakteriologia 2', 'U33', 'Mycobacterium tuberculosis Przeciwciała IgA (anty-M.tuberculosis IgA)'),
       ('U', 'Bakteriologia 2', 'U34', 'Mycobacterium tuberculosis Przeciwciała IgG (anty-M.tuberculosis IgG)'),
       ('U', 'Bakteriologia 2', 'U35', 'Mycobacterium tuberculosis Przeciwciała IgG (ilościowo)'),
       ('U', 'Bakteriologia 2', 'U36', 'Mycobacterium tuberculosis Przeciwciała IgM (anty-M. tuberculosis IgM)'),
       ('U', 'Bakteriologia 2', 'U37', 'Mycobacterium tuberculosis complex DNA'),
       ('U', 'Bakteriologia 2', 'U38', 'Mycoplasma pneumoniae Antygen'),
       ('U', 'Bakteriologia 2', 'U39', 'Mycoplasma pneumoniae Przeciwciała IgA (anty-M.pneumoniae IgA)'),
       ('U', 'Bakteriologia 2', 'U40', 'Mycoplasma pneumoniae Przeciwciała IgA (ilościowo)'),
       ('U', 'Bakteriologia 2', 'U41', 'Mycoplasma pneumoniae Przeciwciała IgG (anty-M.pneumoniae IgG)'),
       ('U', 'Bakteriologia 2', 'U42', 'Mycoplasma pneumoniae IgG/ IgA Przeciwciała'),
       ('U', 'Bakteriologia 2', 'U43', 'Mycoplasma pneumoniae Przeciwciała IgM (anty-M.pneumoniae IgM)'),
       ('U', 'Bakteriologia 2', 'U44', 'Mycoplasma pneumoniae Przeciwciała IgM - test potwierdzenia'),
       ('U', 'Bakteriologia 2', 'U45', 'Mycoplasma pneumoniae Przeciwciała IgG/ IgM'),
       ('U', 'Bakteriologia 2', 'U46', 'Neisseria gonorrhoeae DNA'),
       ('U', 'Bakteriologia 2', 'U47', 'Neisseria meningitidis (Grupy A-D, X-Z, W135) Antygen (surowica poliwalentna)'),
       ('U', 'Bakteriologia 2', 'U48', 'Neisseria meningitidis (Grupa A, B, C, D, X, Y, Z, W135, 29E) Antygen (surowica monowalentna)');
INSERT INTO `icd` (`code1`, `name1`, `code2`, `name2`)
VALUES ('U', 'Bakteriologia 2', 'U49', 'Neisseria meningitidis B / E. coli K1 Antygen'),
       ('U', 'Bakteriologia 2', 'U50', 'Neisseria meningitidis A,B / E.coli K1, C, Y/W Antygen (rozpuszczalne)'),
       ('U', 'Bakteriologia 2', 'U51', 'Neisseria meningitidis A,C,Y,W135 Antygen (lateks poliwalentny)'),
       ('U', 'Bakteriologia 2', 'U52', 'Proteus spp. Antygen (surowica monowalentna)'),
       ('U', 'Bakteriologia 2', 'U53', 'Pseudomonas aeruginosa Antygen (surowica poliwalentna)'),
       ('U', 'Bakteriologia 2', 'U54', 'Pseudomonas aeruginosa Antygen (surowica monowalentna)'),
       ('U', 'Bakteriologia 2', 'U55', 'Salmonella spp. Antygen (surowica poliwalentna)'),
       ('U', 'Bakteriologia 2', 'U56', 'Salmonella spp. Antygen (surowica monowalentna)'),
       ('U', 'Bakteriologia 2', 'U57', 'Salmonella spp. Przeciwciała IgA'),
       ('U', 'Bakteriologia 2', 'U58', 'Salmonella spp. Przeciwciała IgG'),
       ('U', 'Bakteriologia 2', 'U59', 'Salmonella spp. Przeciwciała IgM'),
       ('U', 'Bakteriologia 2', 'U60', 'Salmonella Typhi, Salmonella Paratyphi A B C Antygen (surowica poliwalentna)'),
       ('U', 'Bakteriologia 2', 'U61', 'Shigella boydii Antygen (surowica poliwalentna)'),
       ('U', 'Bakteriologia 2', 'U62', 'Shigella Dysenteriae Antygen (surowica monowalentna)'),
       ('U', 'Bakteriologia 2', 'U63', 'Shigella dysenteriae Antygen (surowica poliwalentna)'),
       ('U', 'Bakteriologia 2', 'U64', 'Shigella Flexneri Antygen (surowica poliwalentna)'),
       ('U', 'Bakteriologia 2', 'U65', 'Shigella Sonnei Antygen (surowica polwalentna)'),
       ('U', 'Bakteriologia 2', 'U66', 'Staphylococcus aureus Antygen'),
       ('U', 'Bakteriologia 2', 'U67', 'Staphylococcus aureus Antygen PBP2,'),
       ('U', 'Bakteriologia 2', 'U68', 'Staphylococcus aureus Antygen enterotoksyny'),
       ('U', 'Bakteriologia 2', 'U69', 'Staphylococcus aureus Antygen TSST-1'),
       ('U', 'Bakteriologia 2', 'U70', 'Staphylococcus aureus DNA'),
       ('U', 'Bakteriologia 2', 'U71', 'Staphylococcus aureus gen mec A'),
       ('U', 'Bakteriologia 2', 'U72', 'Streptococcus pneumoniae Antygen'),
       ('U', 'Bakteriologia 2', 'U73', 'Streptococcus pneumoniae DNA'),
       ('U', 'Bakteriologia 2', 'U74', 'Streptococcus Gr. A,B,C,D,F,G Antygen (lateks monowalentny)'),
       ('U', 'Bakteriologia 2', 'U75', 'Streptococcus pyogenes Gr. A Przeciwciała (Antystreptolizyna O)'),
       ('U', 'Bakteriologia 2', 'U76', 'Streptococcus Gr. B Antygen'),
       ('U', 'Bakteriologia 2', 'U77', 'Streptococcus Gr. B Antygen (B I, B II, B III)'),
       ('U', 'Bakteriologia 2', 'U78', 'Streptococcus Gr. B DNA'),
       ('U', 'Bakteriologia 2', 'U79', 'Treponema pallidum Przeciwciała (anty- T.pallidum)'),
       ('U', 'Bakteriologia 2', 'U80', 'Treponema pallidum IgG Przeciwciała (anty-T.pallidum IgG)'),
       ('U', 'Bakteriologia 2', 'U81', 'Treponema pallidum Przeciwciała IgG - test potwierdzenia'),
       ('U', 'Bakteriologia 2', 'U82', 'Treponema pallidum Przeciwciała IgM (anty-T.pallidum IgM)'),
       ('U', 'Bakteriologia 2', 'U83', 'Treponema pallidum Przeciwciała IgM - test potwierdzenia'),
       ('U', 'Bakteriologia 2', 'U84', 'Treponema pallidum Przeciwciała IgG/ IgM (anty-T. pallidum IgG/ IgM)'),
       ('U', 'Bakteriologia 2', 'U85', 'Treponema pallidum Antygen'),
       ('U', 'Bakteriologia 2', 'U86', 'Vibrio cholerae Antygen (surowica poliwalentna 0:1)'),
       ('U', 'Bakteriologia 2', 'U87', 'Yersinia Przeciwciała IgG (anty-Yersinia IgG)'),
       ('U', 'Bakteriologia 2', 'U88', 'Yersinia Przeciwciała IgM (anty-Yersinia IgM)'),
       ('U', 'Bakteriologia 2', 'U89', 'Yersinia Przeciwciała IgA (anty-Yersinia IgA)'),
       ('U', 'Bakteriologia 2', 'U90', 'Yersinia Przeciwciała IgG/ IgM (anty-Yersinia IgG/ IgM)'),
       ('U', 'Bakteriologia 2', 'U91', 'Yersinia Przeciwciała IgG/ A (anty-Yersinia IgG/ A)'),
       ('U', 'Bakteriologia 2', 'U92', 'Yersinia enterocolitica Przeciwciała IgA'),
       ('U', 'Bakteriologia 2', 'U93', 'Yersinia enterocolitica Przeciwciała IgA - test potwierdzenia'),
       ('U', 'Bakteriologia 2', 'U94', 'Yersinia enterocolitica Przeciwciała IgG'),
       ('U', 'Bakteriologia 2', 'U95', 'Yersinia enterocolitica Przeciwciała IgG - test potwierdzenia'),
       ('U', 'Bakteriologia 2', 'U96', 'Yersinia enterocolitica Przeciwciała IgM'),
       ('U', 'Bakteriologia 2', 'U97', 'Yersinia enterocolitica Przeciwciała IgA/IgM'),
       ('U', 'Bakteriologia 2', 'U98', 'Yersinia enterocolitica Przeciwciała IgA/ IgM - test potwierdzenia'),
       ('U', 'Bakteriologia 2', 'U99', 'Yersinia Antygen (surowica monowalentna O:3, O:9)'),
       ('V', 'Wirusologia 2', 'V01', 'Wirus Parainfluenzy typ 2 Przeciwciała IgG/ IgM (anty-Parainfluenza 2 IgG/ IgM)'),
       ('V', 'Wirusologia 2', 'V02', 'Wirus Parainfluenzy typ 2 Przeciwciała IgG'),
       ('V', 'Wirusologia 2', 'V03', 'Wirus Parainfluenzy typ 1 + 2 Antygen'),
       ('V', 'Wirusologia 2', 'V04', 'Wirus Parainfluenzy typ 3 IgG Przeciwciała'),
       ('V', 'Wirusologia 2', 'V05', 'Wirus Parainfluenzy typ 3 IgG/ IgM Przeciwciała (anty-Parainfluenza 3 IgG/ IgM)'),
       ('V', 'Wirusologia 2', 'V06', 'Wirus Parainfluenzy typ 3 Antygen'),
       ('V', 'Wirusologia 2', 'V07', 'Wirus Parainfluenzy typ 1, 2, 3 Przeciwciała IgA (anty-Parainfluenza 1/2/3 IgA)'),
       ('V', 'Wirusologia 2', 'V08', 'Wirus Parainfluenzy typ 1, 2, 3 Przeciwciała IgA (anty-Parainfluenza 1/2/3 IgA) (ilościowo)'),
       ('V', 'Wirusologia 2', 'V09', 'Wirus Parainfluenzy typ 1, 2, 3 Przeciwciała IgG (anty-Parainfluenza 1/2/3 IgG)'),
       ('V', 'Wirusologia 2', 'V10', 'Wirus Parainfluenzy typ 1, 2, 3 Przeciwciała IgM (anty-Parainfluenza 1/2/3 IgM)'),
       ('V', 'Wirusologia 2', 'V11', 'Wirus Parainfluenzy typ 1, 2, 3 Przeciwciała IgG/ IgM (anty-Parainfluenza 1/2/3 IgG/ IgM)'),
       ('V', 'Wirusologia 2', 'V12', 'Wirus Poliomyelitis Przeciwciała IgG (anty-Poliovirus IgG)'),
       ('V', 'Wirusologia 2', 'V13', 'Wirus Poliomyelitis Przeciwciała IgM (anty-Poliovirus IgM)'),
       ('V', 'Wirusologia 2', 'V14', 'Wirus RS Antygen'),
       ('V', 'Wirusologia 2', 'V15', 'Wirus RS Przeciwciała IgA (anty-RSV IgA)'),
       ('V', 'Wirusologia 2', 'V16', 'Wirus RS Przeciwciała IgG (anty-RSV IgG)'),
       ('V', 'Wirusologia 2', 'V17', 'Wirus RS Przeciwciała IgM (anty-RSV IgM)'),
       ('V', 'Wirusologia 2', 'V18', 'Wirus RS Przeciwciała IgG/ IgM (anty-RSV IgG/ IgM)'),
       ('V', 'Wirusologia 2', 'V19', 'Wirus różyczki (Rubella virus) Przeciwciała IgG (anty-Rubella virus IgG)'),
       ('V', 'Wirusologia 2', 'V20', 'Wirus różyczki (Rubella virus) Przeciwciała IgG - test potwierdzenia'),
       ('V', 'Wirusologia 2', 'V21', 'Wirus różyczki (Rubella virus) Przeciwciała IgG (anty-Rubella virus IgG) (ilościowo)'),
       ('V', 'Wirusologia 2', 'V22', 'Wirus różyczki (Rubella virus) Przeciwciała'),
       ('V', 'Wirusologia 2', 'V23', 'Wirus różyczki (Rubella virus) IgM (anty-Rubella virus IgM)'),
       ('V', 'Wirusologia 2', 'V24', 'Wirus różyczki (Rubella virus) Przeciwciała IgM (anty-Rubella virus IgM) (ilościowo)'),
       ('V', 'Wirusologia 2', 'V25', 'Wirus różyczki (Rubella virus) Przeciwciała IgG/ IgM'),
       ('V', 'Wirusologia 2', 'V26', 'Rubella virus + CMV + Toxoplasma Rubella IgG + CMV IgM + Toxo IgG'),
       ('V', 'Wirusologia 2', 'V27', 'Wirus zapalenia wątroby typu A (HAV) Przeciwciała (całkowite)'),
       ('V', 'Wirusologia 2', 'V28', 'Wirus zapalenia wątroby typu A Przeciwciała IgG'),
       ('V', 'Wirusologia 2', 'V29', 'Wirus zapalenia wątroby typu A Przeciwciała IgM'),
       ('V', 'Wirusologia 2', 'V30', 'Wirus zapalenia wątroby typu A + B HAV IgM + HBs Antygen'),
       ('V', 'Wirusologia 2', 'V31', 'Wirus zapalenia wątroby typu B (HBV) Przeciwciała HBc (całkowite)'),
       ('V', 'Wirusologia 2', 'V32', 'Wirus zapalenia wątroby typu B HBc IgM'),
       ('V', 'Wirusologia 2', 'V33', 'Wirus zapalenia wątroby typu B HBc IgM (ilościowo)'),
       ('V', 'Wirusologia 2', 'V34', 'Wirus zapalenia wątroby typu B HBc IgG'),
       ('V', 'Wirusologia 2', 'V35', 'Wirus zapalenia wątroby typu B HBe Antygen'),
       ('V', 'Wirusologia 2', 'V36', 'Wirus zapalenia wątroby typu B HBe/anty Hbe'),
       ('V', 'Wirusologia 2', 'V37', 'Wirus zapalenia wątroby typu B PrzeciwciałaHBc IgG + HBs'),
       ('V', 'Wirusologia 2', 'V38', 'Wirus zapalenia wątroby typu B HBe Przeciwciała'),
       ('V', 'Wirusologia 2', 'V39', 'Wirus zapalenia wątroby typu B HBs Antygen'),
       ('V', 'Wirusologia 2', 'V40', 'Wirus zapalenia wątroby typu B HBs Antygen (ilościowo)'),
       ('V', 'Wirusologia 2', 'V41', 'Wirus zapalenia wątroby typu B HBs Antygen (potwierdzajacy)'),
       ('V', 'Wirusologia 2', 'V42', 'Wirus zapalenia wątroby typu B Przeciwciała HBs'),
       ('V', 'Wirusologia 2', 'V43', 'Wirus zapalenia wątroby typu B HBc IgG/HBs Przeciwciała'),
       ('V', 'Wirusologia 2', 'V44', 'Wirus zapalenia wątroby typu B HBs Antygen + HBc IgM'),
       ('V', 'Wirusologia 2', 'V45', 'Wirus zapalenia wątroby typu B HBs Antygen + Przeciwciała HBs + HBc IgG'),
       ('V', 'Wirusologia 2', 'V46', 'Wirus zapalenia wątroby typu B HBs Antygen + Przeciwciała + HBc IgG + HBc IgM'),
       ('V', 'Wirusologia 2', 'V47', 'Wirus zapalenia wątroby typu B HBV-DNA'),
       ('V', 'Wirusologia 2', 'V48', 'Wirus zapalenia wątroby typu C (HCV) Przeciwciała (anty-HCV)'),
       ('V', 'Wirusologia 2', 'V49', 'Wirus zapalenia wątroby typu C Przeciwciała (potwierdzający)'),
       ('V', 'Wirusologia 2', 'V50', 'Wirus zapalenia wątroby typu C Przeciwciała IgM'),
       ('V', 'Wirusologia 2', 'V51', 'Wirus zapalenia wątroby typu C Przeciwciała IgM - test potwierdzenia'),
       ('V', 'Wirusologia 2', 'V52', 'Wirus zapalenia wątroby typu C Przeciwciała IgG'),
       ('V', 'Wirusologia 2', 'V53', 'Wirus zapalenia wątroby typu C Przeciwciała IgG - test potwierdzenia'),
       ('V', 'Wirusologia 2', 'V54', 'Wirus zapalenia wątroby typu C HCVcAntygen (antygen rdzeniowy)'),
       ('V', 'Wirusologia 2', 'V55', 'Wirus zapalenia wątroby typu C HCV-RNA'),
       ('V', 'Wirusologia 2', 'V56', 'Wirus zapalenia wątroby typu C HCV-RNA (ilościowo)'),
       ('V', 'Wirusologia 2', 'V57', 'Wirus zapalenia wątroby typu D (HDV) Antygen'),
       ('V', 'Wirusologia 2', 'V58', 'Wirus zapalenia wątroby typu D Przeciwciała'),
       ('V', 'Wirusologia 2', 'V59', 'Wirus zapalenia wątroby typu D Przeciwciała (ilościowo)'),
       ('V', 'Wirusologia 2', 'V60', 'Wirus zapalenia wątroby typu D Przeciwciała IgG'),
       ('V', 'Wirusologia 2', 'V61', 'Wirus zapalenia wątroby typu D Przeciwciała IgM'),
       ('V', 'Wirusologia 2', 'V62', 'Wirus zapalenia wątroby typu E (HEV) Przeciwciała'),
       ('V', 'Wirusologia 2', 'V63', 'Wirus zapalenia wątroby typu E Przeciwciała IgG'),
       ('V', 'Wirusologia 2', 'V64', 'Wirus zapalenia wątroby typu E Przeciwciała IgM'),
       ('V', 'Wirusologia 2', 'V65', 'Wirus zapalenia wątroby typu E Przeciwciała IgG/ IgM'),
       ('V', 'Wirusologia 2', 'V66', 'Wirus zapalenia mózgu zachodniego Nilu Przeciwciała IgG'),
       ('V', 'Wirusologia 2', 'V67', 'Wirus Varicella-Zoster Przeciwciała IgA (anty-Varicella-Zoster IgA)'),
       ('V', 'Wirusologia 2', 'V68', 'Wirus Varicella-Zoster Przeciwciała IgG (anty-Varicella-Zoster IgG)'),
       ('V', 'Wirusologia 2', 'V69', 'Wirus Varicella-Zoster Przeciwciała IgM (anty-Varicella-Zoster IgM)'),
       ('V', 'Wirusologia 2', 'V70', 'Wirus Varicella-Zoster Przeciwciała IgG/ IgM (anty-Varicella-Zoster IgG/ IgM)'),
       ('V', 'Wirusologia 2', 'V71', 'Wirusy Coxsackie Przeciwciała IgG'),
       ('V', 'Wirusologia 2', 'V72', 'Wirusy Coxsackie Przeciwciała IgM'),
       ('V', 'Wirusologia 2', 'V73', 'Wirusy Coxsackie Przeciwciała IgA'),
       ('V', 'Wirusologia 2', 'V74', 'Wirusy ECHO Przeciwciała IgG'),
       ('V', 'Wirusologia 2', 'V75', 'Wirusy ECHO Przeciwciała IgM'),
       ('V', 'Wirusologia 2', 'V76', 'Wirusy ECHO Przeciwciała IgA'),
       ('V', 'Wirusologia 2', 'V81', 'Wirus Varicella-Zoster VZV-DNA'),
       ('W', 'Mykologia', 'W01', 'Aspergillus spp. Antygen rozpuszczalny - galaktomannan'),
       ('W', 'Mykologia', 'W03', 'Aspergillus spp. Przeciwciała IgA'),
       ('W', 'Mykologia', 'W05', 'Aspergillus spp. Przeciwciała IgG'),
       ('W', 'Mykologia', 'W07', 'Aspergillus spp. Przeciwciała IgM'),
       ('W', 'Mykologia', 'W09', 'Aspergillus fumigatus Przeciwciała'),
       ('W', 'Mykologia', 'W11', 'Aspergillus fumigatus Przeciwciała IgG/ IgM'),
       ('W', 'Mykologia', 'W13', 'A. niger, A. nidulans, A. flavus, A. terreus Przeciwciała'),
       ('W', 'Mykologia', 'W15', 'Blastomyces dermatididis DNA'),
       ('W', 'Mykologia', 'W17', 'Candida spp. Antygen rozpuszczalny – mannan'),
       ('W', 'Mykologia', 'W19', 'Candida albicans Przeciwciała IgG/ IgM (antymannanowe)'),
       ('W', 'Mykologia', 'W21', 'Candida spp. Przeciwciała IgG'),
       ('W', 'Mykologia', 'W23', 'Candida albicans Przeciwciała IgA'),
       ('W', 'Mykologia', 'W25', 'Candida spp. Przeciwciała IgM'),
       ('W', 'Mykologia', 'W27', 'Candida albicans Przeciwciała'),
       ('W', 'Mykologia', 'W29', 'Coccidioides immitis DNA'),
       ('W', 'Mykologia', 'W31', 'Cryptococcus neoformans Antygen (glycuronoxylomannan)'),
       ('W', 'Mykologia', 'W33', 'Histoplasma capsulatum DNA'),
       ('W', 'Mykologia', 'W35', 'Pneumocystis carinii (jirovecii) Antygen (oocysty)'),
       ('X', 'Parazytologia', 'X01', 'Ascaris lumbricoides Przeciwciała IgG (anty-Ascaris lumbricoides)'),
       ('X', 'Parazytologia', 'X03', 'Cryptosporidium Antygen (Cryptosporidium Antygen)'),
       ('X', 'Parazytologia', 'X05', 'Echinococcus granulosus Przeciwciała IgG (anty-Echinococcus IgG)'),
       ('X', 'Parazytologia', 'X07', 'Entamoeba histolytica Antygen (Entamoeba histolytica Antygen)'),
       ('X', 'Parazytologia', 'X09', 'Entamoeba histolytica Przeciwciała IgG (anty-Entamoeba histolytica IgG)'),
       ('X', 'Parazytologia', 'X11', 'Entamoeba histolytica Przeciwciała (całkowite)'),
       ('X', 'Parazytologia', 'X13', 'Giardia lamblia Antygen (Giardia lamblia Antygen)'),
       ('X', 'Parazytologia', 'X15', 'Giardia/ Cryptosporidium Antygen'),
       ('X', 'Parazytologia', 'X17', 'Leishmania Przeciwciała IgG (anty-Leishmania IgG)'),
       ('X', 'Parazytologia', 'X19', 'Leishmania Przeciwciała (całkowite)'),
       ('X', 'Parazytologia', 'X21', 'Leishmania Antygen'),
       ('X', 'Parazytologia', 'X23', 'P.f, P.v, P.m., P.o (Malaria) Antygen'),
       ('X', 'Parazytologia', 'X25', 'Plasmodium falciparum Przeciwciała (całkowite)'),
       ('X', 'Parazytologia', 'X27', 'Schistosoma mansoni Przeciwciała IgG (anty-Schistosoma mansoni IgG)'),
       ('X', 'Parazytologia', 'X29', 'Strongyloides Przeciwciała IgG'),
       ('X', 'Parazytologia', 'X31', 'Taenia solium Taenia solium IgG) Przeciwciała IgG (anty-Taenia solium IgG)'),
       ('X', 'Parazytologia', 'X33', 'Toxocara canis Przeciwciała IgG (anty-Toxocara canis IgG)'),
       ('X', 'Parazytologia', 'X35', 'Toxoplasma gondii Przeciwciała'),
       ('X', 'Parazytologia', 'X37', 'Toxoplasma gondii Przeciwciała IgA (anty-Toxoplasma gongii IgA)'),
       ('X', 'Parazytologia', 'X39', 'Toxoplasma gondii Przeciwciała IgA (anty-Toxoplasma gongii IgA) (ilościowo)'),
       ('X', 'Parazytologia', 'X41', 'Toxoplasma gondii Przeciwciała IgG (anty-Toxoplasma gondii IgG)'),
       ('X', 'Parazytologia', 'X43', 'Toxoplasma gondii IgG Przeciwciała (anty-Toxoplasma gondii IgG) (ilościowo)'),
       ('X', 'Parazytologia', 'X45', 'Toxoplasma gondii Przeciwciała IgM (anty-Toxolpasma gondii IgM)'),
       ('X', 'Parazytologia', 'X47', 'Toxoplasma gondii Przeciwciała IgG + IgM Przeciwciała'),
       ('X', 'Parazytologia', 'X49', 'Toxoplasma gondii Awidność Przeciwciała IgG (anty-T. gondii)'),
       ('X', 'Parazytologia', 'X51', 'Toxoplasma gondii Antygen'),
       ('X', 'Parazytologia', 'X53', 'Trichinella spiralis Przeciwciała IgG (anty-Trichinella IgG)'),
       ('X', 'Parazytologia', 'X55', 'Trypanosoma crusi Przeciwciała IgG (Trypanosoma crusi IgG)'),
       ('Y', 'Badania patomorfologiczne', 'Y90', 'Badanie histopatologiczne');
