version: '3.8'
services:
  db:
    image: mysql:8.0.31
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=labo
      - MYSQL_ROOT_PASSWORD=admin!123
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
